name: Ruby on Rails CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: |
          bundle exec rake db:create db:migrate RAILS_ENV=develop
          bundle exec rspec

      - name: Deploy to production (optional)
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Deploy to production"
