name: Ruby on Rails CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-development:
    runs-on: ubuntu-latest

    env:
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
      AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
      AZURE_RECEIPT_ENDPOINT: ${{ secrets.AZURE_RECEIPT_ENDPOINT }}
      BASE_DELIVERY_URL: ${{ secrets.BASE_DELIVERY_URL }}
      BILLING_API_KEY: ${{ secrets.BILLING_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          sudo apt-get update && sudo apt-get install -y imagemagick libpq-dev

      - name: Setup development DB
        run: |
          bundle exec rake db:create db:migrate RAILS_ENV=development

      - name: Precompile assets (needed for Rswag UI)
        run: |
          bundle exec rails assets:precompile RAILS_ENV=development

      - name: Run RSpec tests
        run: |
          bundle exec rspec

      - name: Generate Rswag Swagger docs
        run: |
          bundle exec rake rswag:specs:swaggerize RAILS_ENV=development
