name: Ruby on Rails CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-development:
    runs-on: ubuntu-latest

    env:
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
      AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
      AZURE_RECEIPT_ENDPOINT: ${{ secrets.AZURE_RECEIPT_ENDPOINT }}
    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          sudo apt-get update && sudo apt-get install -y \
            imagemagick \
      - name: Run tests
        run: |
          bundle exec rake db:create db:migrate RAILS_ENV=development
          bundle exec rspec