name: Deploy to Oracle VM

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.ORACLE_HOST }} << 'EOF'
            cd BillingProject || git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/xintarius/BillingProject.git billingproject && cd billingproject
            git pull origin develop
            
            docker-compose down --remove-orphans
            docker-compose build
            docker-compose up -d
          EOF
